services:
  genjishimada-ocr-dev:
    container_name: genjishimada-ocr-dev
    build:
      context: .
    networks:
      - genji-network
    restart: unless-stopped

networks:
  genji-network:
    external: true
